FROM golang:1.24 as builder

WORKDIR /app
COPY . .
RUN go build -o server ./api/cmd/server

FROM debian:stable-slim
WORKDIR /app
COPY --from=builder /app/server /app/server
ENV PORT=8080
CMD ["/app/server"]
